In [21]:
import numpy as np

In [22]:
arr = np.zeros(shape=(5,5), dtype="int")
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [23]:
arr = np.ones(shape=(10,10), dtype="float") * 8
arr

array([[8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [24]:
arr = np.arange(10,100)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [25]:
arr = np.arange(10,100).reshape(9,10)
arr

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [26]:
arr = np.eye(N=8,dtype="int")
arr

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [27]:
arr = np.diag(np.arange(10))
arr

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [28]:
arr = np.ones(shape=(4,4),dtype="int")
arr
arr = np.pad(arr * 5 ,pad_width=1)
arr

array([[0, 0, 0, 0, 0, 0],
       [0, 5, 5, 5, 5, 0],
       [0, 5, 5, 5, 5, 0],
       [0, 5, 5, 5, 5, 0],
       [0, 5, 5, 5, 5, 0],
       [0, 0, 0, 0, 0, 0]])

In [29]:
arr = np.zeros(shape=(6,6), dtype="int")
arr
arr[::2,::2] = 2
arr[1::2,::2] = 4
arr

array([[2, 0, 2, 0, 2, 0],
       [4, 0, 4, 0, 4, 0],
       [2, 0, 2, 0, 2, 0],
       [4, 0, 4, 0, 4, 0],
       [2, 0, 2, 0, 2, 0],
       [4, 0, 4, 0, 4, 0]])

In [30]:
arr = np.array( 
    [
        [4.99,3.49,9.99],
        [1.99,9.99,14.99],
        [14.99,2.39,7.29],
    ]
)

result = np.zeros_like(arr)
result

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
arr = np.array( 
    [
        [4.99,3.49,9.99],
        [1.99,9.99,14.99],
        [14.99,2.39,7.29],
    ]
)

result = np.full_like(arr,9.99)
result

array([[9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99]])

In [32]:
arr = np.tri(N=6)
arr

array([[1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1.]])

In [33]:
arr = np.array(
    [
        [False,True,True,False,True],
        [False,False,True,True,True]
    ]
)

arr = arr.astype("int")
arr

array([[0, 1, 1, 0, 1],
       [0, 0, 1, 1, 1]])

In [34]:
rates = [
    [1.97, 1.04, 1.35, 2.17, 2.29, 4.38],
    [1.34, 2.04, 1.37, 2.09, 1.29, 3.38],
]
arr = np.asarray(rates)
arr

array([[1.97, 1.04, 1.35, 2.17, 2.29, 4.38],
       [1.34, 2.04, 1.37, 2.09, 1.29, 3.38]])

In [35]:
title = '30 Days of Python Code - Numpy Challange'
tokens = title.split(' ')
arr = np.asarray(tokens).reshape(2,-1)
arr

array([['30', 'Days', 'of', 'Python'],
       ['Code', '-', 'Numpy', 'Challange']], dtype='<U9')

In [36]:
arr = np.tile(np.arange(10),(5,1))
arr

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [37]:
 
arr = np.array(
    [
        [[3, 2, 4, 0, 1, 3], [5, 0, 4, 4, 4, 1], [3, 2, 4, 1, 1, 4]],
        [[5, 5, 4, 5, 1, 3], [2, 2, 5, 2, 4, 0], [5, 1, 3, 4, 2, 3]],
    ]
)

result = np.ones_like(arr)
result

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]])

In [41]:
arr = np.concatenate(
    (
        np.linspace(0,1,11).reshape(1,-1),
        np.zeros((4,11))
    ),
    axis =0
)

arr

array([[0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ]])

In [42]:
x = np.linspace(0, 1, 11)
y = np.linspace(0, 1, 11)
 
xx, yy = np.meshgrid(x, y)
 
print(xx)
print(yy)

[[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]]
[[0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]
 [0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3]
 [0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
 [0.6 0.6 0.6 0.6 0.6 0.6 0.6 0.6 0.6 0.6 0.6]
 [0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7]
 [0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8]
 [0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9]
 [1.  1.  1.

In [43]:
string_data = '4 2 6 2 7 10 6 2 14'
arr = np.fromstring(string_data, dtype='int16', sep=' ')
 
print(arr)

[ 4  2  6  2  7 10  6  2 14]


In [44]:
arr = np.array(
    [
        [
            [0.0, 2.0, 0.5, 1.0],
            [0.0, 2.0, 0.0, 3.0],
            [0.0, 4.0, 0.0, 0.0],
        ],
        [
            [0.0, 0.5, 0.0, 0.2],
            [0.0, 0.4, 0.0, 5.0],
            [0.0, 0.0, 1.0, 0.0],
        ],
    ],
    dtype='float32',
)

print(arr)

[[[0.  2.  0.5 1. ]
  [0.  2.  0.  3. ]
  [0.  4.  0.  0. ]]

 [[0.  0.5 0.  0.2]
  [0.  0.4 0.  5. ]
  [0.  0.  1.  0. ]]]
