In [1]:
import numpy as np

#### 23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [2]:
arr2d = np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr = arr2d[0]
arr

array([0, 1, 2, 3, 4])

#### 24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [3]:
arr2d = np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr = arr2d[1]
arr

array([5, 6, 7, 8, 9])

#### 25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [5]:
arr2d = np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr = arr2d[:2,2]
arr

array([2, 7])

#### 26. Create a 10x10 array with random values and find the minimum and maximum values

In [8]:
arr = np.random.rand(10,10)
arr
print(np.min(arr))
print(np.max(arr))

0.008874998270073542
0.992261808696434


#### 27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [10]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

arr = np.intersect1d(a,b)
arr

array([2, 4])

#### 28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [11]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

arr = np.where(a == b)
arr

(array([1, 3, 5, 7], dtype=int64),)

#### 29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [12]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

mask = names != "Will"

result = data[mask]

result


array([[-0.19293144,  0.063772  ,  1.37979068,  1.01187632],
       [ 0.30165929, -0.72654878, -1.53911463,  1.59759268],
       [ 0.58200099,  0.29321807,  1.23100019,  0.47684015],
       [-0.64491673,  0.06492048, -0.46753415,  1.50269943],
       [ 1.03929164, -0.265512  , -0.78848916,  0.12772107]])

#### 30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [13]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

mask = (names != "Will") & (names != "Joe")

result = data[mask]

result

array([[-0.68245051,  0.4175347 ,  0.53222359,  0.83818638],
       [ 0.65012005, -0.204381  , -0.89016055, -1.67964081]])

#### 31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [14]:
arr2d = np.random.uniform(1.0 , 15.0 , size = (5,3))
arr2d

array([[ 2.94541047,  9.51019214,  3.74193194],
       [ 6.44279116,  2.12125308,  7.18277258],
       [14.21547862, 13.47488599,  6.46004444],
       [ 1.51150556,  4.4396604 , 12.74611029],
       [ 8.81409029,  3.17692174,  3.19309551]])

#### 32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [15]:
arr3d = np.random.uniform(1 , 16, size=(2,2,4))
arr3d

array([[[ 8.3643028 ,  9.46101793, 10.84664694,  1.15116554],
        [ 2.68027402,  6.10984282, 11.85680951, 14.31227901]],

       [[ 2.59167582,  4.60676079, 13.51134294,  7.45419464],
        [ 8.48645348, 11.85906928, 13.81655436,  7.42371505]]])

#### 33. Swap axes of the array you created in Question 32

In [18]:
array_3d_swapped = np.swapaxes(arr3d, 0, 2)
print(array_3d_swapped)

[[[ 8.3643028   2.59167582]
  [ 2.68027402  8.48645348]]

 [[ 9.46101793  4.60676079]
  [ 6.10984282 11.85906928]]

 [[10.84664694 13.51134294]
  [11.85680951 13.81655436]]

 [[ 1.15116554  7.45419464]
  [14.31227901  7.42371505]]]
