In [1]:
import numpy as np

#### 45. How to Convert higher dimension into one dimension?

In [2]:
# Create a higher-dimensional array
higher_dimensional_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Flatten the array to one dimension
one_dimensional_array = higher_dimensional_array.flatten()

print("Higher-dimensional Array:")
print(higher_dimensional_array)
print("\nFlattened 1D Array:")
print(one_dimensional_array)

Higher-dimensional Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flattened 1D Array:
[1 2 3 4 5 6 7 8 9]


#### 46. Convert one dimension to higher dimension?

In [3]:

# Create a one-dimensional array
one_dimensional_array = np.array([1, 2, 3, 4, 5, 6])

# Convert to a higher-dimensional array, for example, 2x3
higher_dimensional_array = one_dimensional_array.reshape(2, 3)

print("One-dimensional Array:")
print(one_dimensional_array)
print("\nConverted 2x3 Higher-dimensional Array:")
print(higher_dimensional_array)

One-dimensional Array:
[1 2 3 4 5 6]

Converted 2x3 Higher-dimensional Array:
[[1 2 3]
 [4 5 6]]


#### 47. Create 5x5 an array and find the square of an array?

In [4]:
# Create a 5x5 array
array_5x5 = np.random.rand(5, 5)

# Find the square of each element in the array
array_squared = np.square(array_5x5)

print("Original 5x5 Array:")
print(array_5x5)
print("\nArray after squaring each element:")
print(array_squared)

Original 5x5 Array:
[[0.63271498 0.01934633 0.20518578 0.03405324 0.53696285]
 [0.2921336  0.4414863  0.03504864 0.99749671 0.82639148]
 [0.15434572 0.79741023 0.16259484 0.28139906 0.96620204]
 [0.13746353 0.65074825 0.289177   0.63307506 0.21816344]
 [0.78747365 0.41041402 0.69688404 0.14079793 0.42263494]]

Array after squaring each element:
[[4.00328240e-01 3.74280365e-04 4.21012057e-02 1.15962304e-03
  2.88329107e-01]
 [8.53420417e-02 1.94910154e-01 1.22840696e-03 9.94999685e-01
  6.82922873e-01]
 [2.38226014e-02 6.35863070e-01 2.64370804e-02 7.91854289e-02
  9.33546386e-01]
 [1.88962210e-02 4.23473283e-01 8.36233352e-02 4.00784032e-01
  4.75952876e-02]
 [6.20114745e-01 1.68439665e-01 4.85647361e-01 1.98240583e-02
  1.78620289e-01]]


#### 48. Create 5x6 an array and find the mean?

In [5]:
# Create a 5x6 array
array_5x6 = np.random.rand(5, 6)

# Calculate the mean of the array
array_mean = np.mean(array_5x6)

print("Original 5x6 Array:")
print(array_5x6)
print("\nMean of the Array:")
print(array_mean)

Original 5x6 Array:
[[0.4819685  0.66295089 0.87965849 0.57656695 0.60455895 0.63691127]
 [0.70187559 0.56747294 0.45670495 0.20337257 0.21637577 0.69890251]
 [0.35526646 0.92453279 0.99690125 0.03737372 0.83423873 0.31177624]
 [0.96163417 0.44747319 0.7814708  0.01918667 0.87402939 0.14775969]
 [0.14649612 0.64743991 0.50429334 0.65765347 0.20276648 0.24344057]]

Mean of the Array:
0.5260350781226936


#### 49. Find the standard deviation of the previous array in Q48?

In [6]:
# Assuming array_5x6 is the previously created 5x6 array
array_std_dev = np.std(array_5x6)

print("Original 5x6 Array:")
print(array_5x6)
print("\nStandard Deviation of the Array:")
print(array_std_dev)

Original 5x6 Array:
[[0.4819685  0.66295089 0.87965849 0.57656695 0.60455895 0.63691127]
 [0.70187559 0.56747294 0.45670495 0.20337257 0.21637577 0.69890251]
 [0.35526646 0.92453279 0.99690125 0.03737372 0.83423873 0.31177624]
 [0.96163417 0.44747319 0.7814708  0.01918667 0.87402939 0.14775969]
 [0.14649612 0.64743991 0.50429334 0.65765347 0.20276648 0.24344057]]

Standard Deviation of the Array:
0.2808701679170779


#### 50. Find the median of the previous array in Q48?

In [7]:
# Assuming array_5x6 is the previously created 5x6 array
array_median = np.median(array_5x6)

print("Original 5x6 Array:")
print(array_5x6)
print("\nMedian of the Array:")
print(array_median)

Original 5x6 Array:
[[0.4819685  0.66295089 0.87965849 0.57656695 0.60455895 0.63691127]
 [0.70187559 0.56747294 0.45670495 0.20337257 0.21637577 0.69890251]
 [0.35526646 0.92453279 0.99690125 0.03737372 0.83423873 0.31177624]
 [0.96163417 0.44747319 0.7814708  0.01918667 0.87402939 0.14775969]
 [0.14649612 0.64743991 0.50429334 0.65765347 0.20276648 0.24344057]]

Median of the Array:
0.5720199404443039


#### 51. Find the transpose of the previous array in Q48?

In [8]:
# Assuming array_5x6 is the previously created 5x6 array
array_transpose = np.transpose(array_5x6)

print("Original 5x6 Array:")
print(array_5x6)
print("\nTranspose of the Array:")
print(array_transpose)

Original 5x6 Array:
[[0.4819685  0.66295089 0.87965849 0.57656695 0.60455895 0.63691127]
 [0.70187559 0.56747294 0.45670495 0.20337257 0.21637577 0.69890251]
 [0.35526646 0.92453279 0.99690125 0.03737372 0.83423873 0.31177624]
 [0.96163417 0.44747319 0.7814708  0.01918667 0.87402939 0.14775969]
 [0.14649612 0.64743991 0.50429334 0.65765347 0.20276648 0.24344057]]

Transpose of the Array:
[[0.4819685  0.70187559 0.35526646 0.96163417 0.14649612]
 [0.66295089 0.56747294 0.92453279 0.44747319 0.64743991]
 [0.87965849 0.45670495 0.99690125 0.7814708  0.50429334]
 [0.57656695 0.20337257 0.03737372 0.01918667 0.65765347]
 [0.60455895 0.21637577 0.83423873 0.87402939 0.20276648]
 [0.63691127 0.69890251 0.31177624 0.14775969 0.24344057]]


#### 52. Create a 4x4 an array and find the sum of diagonal elements?

In [9]:
# Create a 4x4 array
array_4x4 = np.random.rand(4, 4)

# Find the sum of diagonal elements
diagonal_sum = np.trace(array_4x4)

print("Original 4x4 Array:")
print(array_4x4)
print("\nSum of Diagonal Elements:")
print(diagonal_sum)

Original 4x4 Array:
[[0.58239367 0.58019403 0.17607498 0.32731162]
 [0.74888001 0.08132227 0.1647792  0.53234713]
 [0.98675978 0.89991118 0.0071927  0.88497872]
 [0.17473285 0.50869406 0.49564767 0.36159873]]

Sum of Diagonal Elements:
1.0325073792177344


#### 53. Find the determinant of the previous array in Q52?

In [10]:

# Assuming array_4x4 is the previously created 4x4 array
array_determinant = np.linalg.det(array_4x4)

print("Original 4x4 Array:")
print(array_4x4)
print("\nDeterminant of the Array:")
print(array_determinant)

Original 4x4 Array:
[[0.58239367 0.58019403 0.17607498 0.32731162]
 [0.74888001 0.08132227 0.1647792  0.53234713]
 [0.98675978 0.89991118 0.0071927  0.88497872]
 [0.17473285 0.50869406 0.49564767 0.36159873]]

Determinant of the Array:
0.08550990235591356


#### 54. Find the 5th and 95th percentile of an array?

In [11]:
# Create an array
array_example = np.random.rand(100)

# Find the 5th and 95th percentiles
percentile_5th = np.percentile(array_example, 5)
percentile_95th = np.percentile(array_example, 95)

print("Original Array:")
print(array_example)
print("\n5th Percentile:", percentile_5th)
print("95th Percentile:", percentile_95th)

Original Array:
[0.15214473 0.1375475  0.74355509 0.05547173 0.05274863 0.66671639
 0.72493564 0.85542031 0.24816859 0.18009281 0.15367439 0.78808882
 0.84216944 0.96314415 0.42910374 0.92948988 0.13669198 0.42212458
 0.81635637 0.33190885 0.54712357 0.97233272 0.84080876 0.21372891
 0.44324131 0.92872108 0.77991849 0.25395289 0.30657316 0.55054215
 0.2783617  0.17975971 0.1480797  0.31515403 0.91118847 0.61452247
 0.43856279 0.48369348 0.33182206 0.8726261  0.05001568 0.99445638
 0.7715511  0.47176371 0.03141186 0.60294763 0.5867543  0.43861251
 0.71068244 0.14391677 0.449641   0.52004888 0.54379481 0.2789324
 0.48348269 0.14409922 0.81344037 0.21836629 0.64792673 0.29986964
 0.74572776 0.986441   0.45514777 0.32054409 0.14805038 0.10621841
 0.29783578 0.24981995 0.71504872 0.45693808 0.653829   0.35325953
 0.94576377 0.36936687 0.26583195 0.15023605 0.69294767 0.7810982
 0.40195409 0.8842264  0.73698187 0.25934698 0.75240287 0.74757787
 0.51294076 0.60014972 0.77053034 0.92562658 0.0

#### 55. How to find if a given array has any null values?

In [12]:
# Create an array with some null values
array_with_nulls = np.array([1.0, 2.0, np.nan, 4.0, np.nan, 6.0])

# Check for null values
has_null_values = np.isnan(array_with_nulls).any()

print("Array with Null Values:")
print(array_with_nulls)
print("\nDoes the array have any null values?", has_null_values)

Array with Null Values:
[ 1.  2. nan  4. nan  6.]

Does the array have any null values? True
