### 1. Import the numpy package under the name np

In [2]:
import numpy as np

### 2. Create a null vector of size 10 

In [3]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 3. Create a vector with values ranging from 10 to 49

In [4]:
arr = np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 4. Find the shape of previous array in question 3

In [5]:
arr.shape

(40,)

### 5. Print the type of the previous array in question 3

In [6]:
type(arr)

numpy.ndarray

### 6. Print the numpy version and the configuration


In [7]:
print(np.__version__)
print(np.show_config())

1.24.3
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SC/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SC/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SC/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SC/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SC/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SC/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SC/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SC/anaconda3\\Library\\include']
S

### 7. Print the dimension of the array in question 3


In [8]:
arr.shape

(40,)

### 8. Create a boolean array with all the True values

In [9]:
arr = np.ones(10, dtype=bool)
arr

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

### 9. Create a two dimensional array




In [10]:
arr_2d = np.array([[1,2,3],[4,5,6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

### 10. Create a three dimensional array



In [11]:
arr_3d = np.array([[[1,2,3],[4,5,6]],[[1,3,5],[2,4,6]]])
arr_3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 3, 5],
        [2, 4, 6]]])

### 11. Reverse a vector (first element becomes last)

In [15]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = a[::-1]
b

array([9, 8, 7, 6, 5, 4, 3, 2, 1])