In [1]:
import numpy as np

In [3]:
np.__version__

'1.24.3'

In [6]:
arr = np.zeros(shape=(5,5), dtype="int16")

print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [7]:
arr = np.ones(shape=(10,10), dtype="float32") * 8

print(arr)

[[8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]]


In [8]:
arr = np.arange(10,100)

print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [9]:
arr = np.arange(10,100).reshape(9,10)

print(arr)

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [10]:
arr = np.eye(N=8, dtype="int16")

print(arr)

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]


In [12]:
arr = np.array(
    [
        [
            [1,2,3,4],
            [5,6,7,8],
            [9,0,1,2],
        ],
        [
            [1,3,5,7],
            [2,4,6,8],
            [3,6,9,2,]
        ]
    ]
)

print(arr)

[[[1 2 3 4]
  [5 6 7 8]
  [9 0 1 2]]

 [[1 3 5 7]
  [2 4 6 8]
  [3 6 9 2]]]


In [13]:
arr = np.array(
    [
        ['4', '3', '6', '2', '1'],
        ['7', '2', '1', '2', '6'],
    ],
    dtype='<U1',
)

arr = arr.astype("float16")

print(arr)

[[4. 3. 6. 2. 1.]
 [7. 2. 1. 2. 6.]]


In [14]:
arr = np.array([1,3,5,7,9])

print(arr)

[1 3 5 7 9]
