In [2]:
import numpy as np

### 12. Create a null vector of size 10 but the fifth value which is 1 

In [3]:
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### 13. Create a 3x3 identity matrix

In [4]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [5]:
arr = np.array([1,2,3,4,5])
arr = arr.astype(float)
arr

array([1., 2., 3., 4., 5.])

### 15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [6]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[0,4,1],[7,2,12]])

arr = arr1 * arr2
arr

array([[ 0,  8,  3],
       [28, 10, 72]])

### 16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [7]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[0,4,1],[7,2,12]])

arr = arr1 - arr2
arr

array([[ 1, -2,  2],
       [-3,  3, -6]])

### 17. Extract all odd numbers from arr with values(0-9)

In [8]:
arr = np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

### 18. Replace all odd numbers to -1 from previous array

In [9]:
arr[:] = -1
arr

array([-1, -1, -1, -1, -1])

### 19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [10]:
arr = np.arange(10)
arr[4:8] = 12
arr

array([ 0,  1,  2,  3, 12, 12, 12, 12,  8,  9])

### 20. Create a 2d array with 1 on the border and 0 inside

In [11]:
rows, cols = 5,5

arr = np.ones((rows , cols),dtype = int)
arr[1:-1,1:-1] = 0
arr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

### 21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [12]:
arr2d  = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[1][1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

### 22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [17]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d[0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])