In [1]:
import numpy as np


In [2]:
arr = np.zeros(shape=(5,5), dtype="int16")

arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int16)

In [3]:
arr = np.ones(shape=(10,10), dtype="float32") * 8

arr

array([[8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]], dtype=float32)

In [4]:
arr = np.arange(10,100)

arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [6]:
arr = np.arange(10,100).reshape(9,10)

arr

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [7]:
arr = np.eye(N=8, dtype="int16")

arr

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]], dtype=int16)

In [8]:
arr = np.array(
    [
        [
            [4, 5, 4, 2],
            [6, 3, 5, 1],
            [5, 2, 1, 2],
        ],
        [
            [7, 2, 3, 1],
            [6, 2, 0, 9],
            [0, 1, 9, 1],
        ],
    ]
)

arr

array([[[4, 5, 4, 2],
        [6, 3, 5, 1],
        [5, 2, 1, 2]],

       [[7, 2, 3, 1],
        [6, 2, 0, 9],
        [0, 1, 9, 1]]])

In [9]:
arr = np.array(
    [
        ['4', '3', '6', '2', '1'],
        ['7', '2', '1', '2', '6'],
    ],
)

arr = arr.astype("float16")

arr

array([[4., 3., 6., 2., 1.],
       [7., 2., 1., 2., 6.]], dtype=float16)

In [10]:
arr = np.diag(np.arange(10))

arr

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [14]:
arr = np.ones(shape=(4,4), dtype="int")
arr = np.pad(arr * 5, pad_width=1)
arr

array([[0, 0, 0, 0, 0, 0],
       [0, 5, 5, 5, 5, 0],
       [0, 5, 5, 5, 5, 0],
       [0, 5, 5, 5, 5, 0],
       [0, 5, 5, 5, 5, 0],
       [0, 0, 0, 0, 0, 0]])

In [21]:
arr = np.zeros(shape=(6,6), dtype="int")
arr[::2,::2] = 2
arr[1::2,::2] = 4
arr

array([[2, 0, 2, 0, 2, 0],
       [4, 0, 4, 0, 4, 0],
       [2, 0, 2, 0, 2, 0],
       [4, 0, 4, 0, 4, 0],
       [2, 0, 2, 0, 2, 0],
       [4, 0, 4, 0, 4, 0]])

In [22]:
arr = np.array( 
    [
        [4.99,3.49,9.99],
        [1.99,9.99,14.99],
        [14.99,2.39,7.29],
    ]
)

result = np.zeros_like(arr)
result

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
arr = np.array( 
    [
        [4.99,3.49,9.99],
        [1.99,9.99,14.99],
        [14.99,2.39,7.29],
    ]
)

result = np.full_like(arr,9.99)
result

array([[9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99]])

In [24]:
arr = np.tri(N=6)
arr

array([[1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1.]])

In [26]:
arr = np.array(
    [
        [False,True,True,False,True],
        [False,False,True,True,True]
    ]
)

arr = arr.astype("int")
arr

array([[0, 1, 1, 0, 1],
       [0, 0, 1, 1, 1]])

In [27]:
arr = np.array([[1,2,3,4,5,6],[1,3,5,7,9,0]])
arr

array([[1, 2, 3, 4, 5, 6],
       [1, 3, 5, 7, 9, 0]])