In [1]:
import numpy as np

#### 34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [2]:
arr = np.random.rand(10)
arr_sqrt = np.sqrt(arr)
arr_sqrt[arr_sqrt < 0.5] = 0
print(arr_sqrt)

[0.8180953  0.86616218 0.71019618 0.61445599 0.62000701 0.78844528
 0.         0.5460569  0.51581654 0.        ]


#### 35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [3]:

# Create two random arrays of range 12
arr1 = np.random.rand(12)
arr2 = np.random.rand(12)

# Make an array with the maximum values between each element of the two arrays
max_values = np.maximum(arr1, arr2)

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Maximum values between arrays:", max_values)


Array 1: [0.66182468 0.32729661 0.43376447 0.75221442 0.39637627 0.53654219
 0.37518886 0.93293727 0.32998755 0.36788233 0.08708702 0.44076064]
Array 2: [0.39181291 0.30629825 0.95548386 0.19291124 0.95939057 0.61007571
 0.59601497 0.70178262 0.01227686 0.01668962 0.40279933 0.39788952]
Maximum values between arrays: [0.66182468 0.32729661 0.95548386 0.75221442 0.95939057 0.61007571
 0.59601497 0.93293727 0.32998755 0.36788233 0.40279933 0.44076064]


#### 36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [4]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

# Find unique names
unique_names = np.unique(names)

# Sort the unique names
sorted_unique_names = np.sort(unique_names)

print("Original Names:", names)
print("Unique and Sorted Names:", sorted_unique_names)

Original Names: ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
Unique and Sorted Names: ['Bob' 'Joe' 'Will']


#### 37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [5]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])

# Remove items present in array b from array a
result = np.setdiff1d(a, b)

print("Array a:", a)
print("Array b:", b)
print("Result after removing items present in b from a:", result)

Array a: [1 2 3 4 5]
Array b: [5 6 7 8 9]
Result after removing items present in b from a: [1 2 3 4]


#### 38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [6]:
sampleArray = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
newColumn = np.array([[10, 10, 10]])

# Delete column two
sampleArray = np.delete(sampleArray, 1, axis=1)

# Insert the new column in its place
sampleArray = np.insert(sampleArray, 1, newColumn, axis=1)

print("Original Array:")
print(sampleArray)

Original Array:
[[34 10 73]
 [82 10 12]
 [53 10 66]]


#### 39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [7]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

# Calculate the dot product
dot_product = np.dot(x, y)  # or simply x @ y

print("Matrix x:")
print(x)
print("\nMatrix y:")
print(y)
print("\nDot Product:")
print(dot_product)

Matrix x:
[[1. 2. 3.]
 [4. 5. 6.]]

Matrix y:
[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]

Dot Product:
[[ 28.  64.]
 [ 67. 181.]]


#### 40. Generate a matrix of 20 random values and find its cumulative sum

In [8]:
# Generate a matrix of 20 random values
random_matrix = np.random.rand(4, 5)

# Calculate the cumulative sum
cumulative_sum_matrix = np.cumsum(random_matrix)

print("Original Matrix:")
print(random_matrix)
print("\nCumulative Sum Matrix:")
print(cumulative_sum_matrix)

Original Matrix:
[[0.80356823 0.78546011 0.35265774 0.78138178 0.65378966]
 [0.73331497 0.98810062 0.58736155 0.74616503 0.26337128]
 [0.53180446 0.43736184 0.50706418 0.19922863 0.96000449]
 [0.73245193 0.10591721 0.15943472 0.15511637 0.05286884]]

Cumulative Sum Matrix:
[ 0.80356823  1.58902834  1.94168608  2.72306786  3.37685752  4.1101725
  5.09827311  5.68563466  6.43179969  6.69517097  7.22697543  7.66433727
  8.17140145  8.37063008  9.33063457 10.0630865  10.16900371 10.32843842
 10.4835548  10.53642364]


#### 41. Convert a 1D array to a 2D array with 2 rows?

In [9]:

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Convert to a 2D array with 2 rows
arr_2d = arr_1d.reshape(2, -1)

print("Original 1D array:")
print(arr_1d)
print("\nConverted 2D array with 2 rows:")
print(arr_2d)

Original 1D array:
[1 2 3 4 5 6 7 8]

Converted 2D array with 2 rows:
[[1 2 3 4]
 [5 6 7 8]]


#### 42. How to stack two arrays vertically?

In [10]:
# Create two arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Stack the arrays vertically
result = np.vstack((array1, array2))

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nStacked result vertically:")
print(result)

Array 1:
[1 2 3]

Array 2:
[4 5 6]

Stacked result vertically:
[[1 2 3]
 [4 5 6]]


#### 43. How to stack two arrays horizontally?

In [11]:
# Create two arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Stack the arrays horizontally
result = np.hstack((array1, array2))

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nStacked result horizontally:")
print(result)

Array 1:
[1 2 3]

Array 2:
[4 5 6]

Stacked result horizontally:
[1 2 3 4 5 6]


#### 44.  How to convert an array of arrays into a flat 1d array?

In [12]:
# Create an array of arrays
array_of_arrays = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Convert to a flat 1D array
flat_array = np.concatenate(array_of_arrays).ravel()

print("Array of Arrays:")
print(array_of_arrays)
print("\nFlat 1D Array:")
print(flat_array)

Array of Arrays:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flat 1D Array:
[1 2 3 4 5 6 7 8 9]
